import type { FontFileWeight, FontWeight } from "./types";

/** Env var that lets a deployment re-point every self-hosted font at once. */
export const selfHostBaseUrlEnvKey = "FONT_SELF_HOST_BASE_URL";

/**
 * One self-hosted font family.
 *
 * Paste entries here (or register them at runtime with
 * `registerSelfHostedFontOverride`) to serve a font from your own domain or
 * from a local path instead of `fonts.gstatic.com`.
 *
 * `files` is intentionally sparse — only the weights you actually ship. Keys
 * are the upright weight (`"400"`, `"700"`, …) or the same weight with an
 * `italic` suffix; values are either absolute URLs or root-relative paths
 * (`/fonts/noto-sans-sc-400-subset.ttf`). Root-relative and bare filenames get
 * `FONT_SELF_HOST_BASE_URL` prepended when it is set.
 *
 * Entries are merged into the generated `webfontlist.json` **at runtime** in
 * `index.ts`: never hand-edit `webfontlist.json`, it is regenerated by
 * `tooling/fonts/generate.ts` and your edits would be wiped.
 */
export type SelfHostedFontOverride = {
	/** Family name as it appears in the resume typography, e.g. "Noto Sans SC". */
	family: string;
	/** Weights this deployment provides. Merged over the generated weights. */
	weights: FontWeight[];
	/** Weight (or weight + "italic") → URL or root-relative path. */
	files: Partial<Record<FontFileWeight, string>>;
};

/**
 * The deployment-owned override table. **Empty by default** — the app keeps
 * using `fonts.gstatic.com` until a deployment fills this in.
 */
export const selfHostedFontOverrides: SelfHostedFontOverride[] = [];

/**
 * Runtime registry. Seeded from `selfHostedFontOverrides` so deployments can
 * either edit that array (simple) or call `registerSelfHostedFontOverride`
 * (useful for tests and for wiring a CMS/config file at boot).
 */
const overrideRegistry: SelfHostedFontOverride[] = [...selfHostedFontOverrides];

/** Adds (or replaces, for the same family) one override. Keeps insertion order. */
export function registerSelfHostedFontOverride(override: SelfHostedFontOverride): void {
	const family = override.family?.trim();
	if (!family) return;

	const existingIndex = overrideRegistry.findIndex((entry) => entry.family === family);
	const entry: SelfHostedFontOverride = { ...override, family };

	if (existingIndex >= 0) {
		overrideRegistry[existingIndex] = entry;
		return;
	}

	overrideRegistry.push(entry);
}

/** Drops every runtime-registered override, restoring the static table. */
export function clearSelfHostedFontOverrides(): void {
	overrideRegistry.length = 0;
	overrideRegistry.push(...selfHostedFontOverrides);
}

/**
 * `FONT_SELF_HOST_BASE_URL`, normalised (trimmed, trailing slash removed),
 * or `null` when unset. Read lazily so tests can stub the env.
 */
export function getSelfHostedFontBaseUrl(): string | null {
	if (typeof process === "undefined" || !process.env) return null;

	const raw = process.env[selfHostBaseUrlEnvKey];
	if (typeof raw !== "string") return null;

	const trimmed = raw.trim().replace(/\/+$/, "");
	return trimmed.length > 0 ? trimmed : null;
}

const isAbsoluteUrl = (value: string): boolean => /^(?:[a-z][a-z\d+.-]*:)?\/\//i.test(value);

/**
 * Applies `FONT_SELF_HOST_BASE_URL` to one `files` value.
 * Absolute URLs (`https://…`, `//cdn…`) are left untouched so a deployment can
 * pin a single family to a different host than the rest.
 */
export function resolveSelfHostedFontUrl(value: string, baseUrl: string | null): string {
	if (!baseUrl || isAbsoluteUrl(value)) return value;
	return `${baseUrl}/${value.replace(/^\/+/, "")}`;
}

/** Applies the base URL to a whole `files` map. */
export function resolveSelfHostedFontFiles(
	files: Partial<Record<FontFileWeight, string>>,
	baseUrl: string | null,
): Partial<Record<FontFileWeight, string>> {
	const resolved: Partial<Record<FontFileWeight, string>> = {};

	for (const [weight, value] of Object.entries(files)) {
		if (typeof value !== "string" || value.length === 0) continue;
		resolved[weight as FontFileWeight] = resolveSelfHostedFontUrl(value, baseUrl);
	}

	return resolved;
}

/**
 * Read-only view of the override table with `FONT_SELF_HOST_BASE_URL` applied.
 * Returns copies, so callers cannot mutate the registry.
 */
export function getSelfHostedOverrides(): SelfHostedFontOverride[] {
	const baseUrl = getSelfHostedFontBaseUrl();

	return overrideRegistry.map((override) => ({
		family: override.family,
		weights: [...override.weights],
		files: resolveSelfHostedFontFiles(override.files, baseUrl),
	}));
}

/** Families that currently have at least one self-hosted file. */
export function getSelfHostedFontFamilies(): string[] {
	return getSelfHostedOverrides()
		.filter((override) => Object.keys(override.files).length > 0)
		.map((override) => override.family);
}

export type FontSourceDescriptor = {
	family: string;
	selfHosted: boolean;
	weights: FontWeight[];
	files: Partial<Record<FontFileWeight, string>>;
};

export type FontSourceReport = {
	/** Normalised `FONT_SELF_HOST_BASE_URL`, or `null` when unset. */
	baseUrl: string | null;
	/** Families served from somewhere the deployment controls. */
	selfHosted: FontSourceDescriptor[];
	/** Families still fetched from a third-party CDN (fonts.gstatic.com). */
	remote: FontSourceDescriptor[];
	/** Distinct hosts the remote fonts are fetched from. */
	remoteHosts: string[];
};
